#ifndef TILE_H
#define TILE_H

#include "GameVariable.h"

void clip_tiles()
{
	//Clip the sprite sheet
	clips[TILE_PATH].x = 00;
	clips[TILE_PATH].y = 00;
	clips[TILE_PATH].w = TILE_WIDTH;
	clips[TILE_PATH].h = TILE_HEIGHT;

	clips[TILE_BLOCK].x = 80;
	clips[TILE_BLOCK].y = 0;
	clips[TILE_BLOCK].w = TILE_WIDTH;
	clips[TILE_BLOCK].h = TILE_HEIGHT;

	clips[TILE_ENEMY].x = 80;
	clips[TILE_ENEMY].y = 0;
	clips[TILE_ENEMY].w = TILE_WIDTH;
	clips[TILE_ENEMY].h = TILE_HEIGHT;

	clips[TILE_TREASURE_T1].x = 0;
	clips[TILE_TREASURE_T1].y = 60;
	clips[TILE_TREASURE_T1].w = TILE_WIDTH;
	clips[TILE_TREASURE_T1].h = TILE_HEIGHT;

	clips[TILE_TREASURE_T2].x = 20;
	clips[TILE_TREASURE_T2].y = 60;
	clips[TILE_TREASURE_T2].w = TILE_WIDTH;
	clips[TILE_TREASURE_T2].h = TILE_HEIGHT;

	clips[TILE_TREASURE_T3].x = 40;
	clips[TILE_TREASURE_T3].y = 60;
	clips[TILE_TREASURE_T3].w = TILE_WIDTH;
	clips[TILE_TREASURE_T3].h = TILE_HEIGHT;

	clips[TILE_TREASURE_T4].x = 60;
	clips[TILE_TREASURE_T4].y = 60;
	clips[TILE_TREASURE_T4].w = TILE_WIDTH;
	clips[TILE_TREASURE_T4].h = TILE_HEIGHT;

	clips[TILE_TREASURE_T5].x = 0;
	clips[TILE_TREASURE_T5].y = 80;
	clips[TILE_TREASURE_T5].w = TILE_WIDTH;
	clips[TILE_TREASURE_T5].h = TILE_HEIGHT;

	clips[TILE_TREASURE_T6].x = 20;
	clips[TILE_TREASURE_T6].y = 80;
	clips[TILE_TREASURE_T6].w = TILE_WIDTH;
	clips[TILE_TREASURE_T6].h = TILE_HEIGHT;

	clips[TILE_TREASURE_T7].x = 40;
	clips[TILE_TREASURE_T7].y = 80;
	clips[TILE_TREASURE_T7].w = TILE_WIDTH;
	clips[TILE_TREASURE_T7].h = TILE_HEIGHT;

	clips[TILE_TREASURE_T8].x = 60;
	clips[TILE_TREASURE_T8].y = 80;
	clips[TILE_TREASURE_T8].w = TILE_WIDTH;
	clips[TILE_TREASURE_T8].h = TILE_HEIGHT;

	clips[TILE_WATER_00].x = 20;
	clips[TILE_WATER_00].y = 00;
	clips[TILE_WATER_00].w = TILE_WIDTH;
	clips[TILE_WATER_00].h = TILE_HEIGHT;

	clips[TILE_WATER_01].x = 80;
	clips[TILE_WATER_01].y = 40;
	clips[TILE_WATER_01].w = TILE_WIDTH;
	clips[TILE_WATER_01].h = TILE_HEIGHT;

	clips[TILE_CAVE_00].x = 0;
	clips[TILE_CAVE_00].y = 20;
	clips[TILE_CAVE_00].w = TILE_WIDTH;
	clips[TILE_CAVE_00].h = TILE_HEIGHT;

	clips[TILE_CAVE_01].x = 20;
	clips[TILE_CAVE_01].y = 20;
	clips[TILE_CAVE_01].w = TILE_WIDTH;
	clips[TILE_CAVE_01].h = TILE_HEIGHT;

	clips[TILE_CAVE_10].x = 0;
	clips[TILE_CAVE_10].y = 40;
	clips[TILE_CAVE_10].w = TILE_WIDTH;
	clips[TILE_CAVE_10].h = TILE_HEIGHT;

	clips[TILE_CAVE_11].x = 20;
	clips[TILE_CAVE_11].y = 40;
	clips[TILE_CAVE_11].w = TILE_WIDTH;
	clips[TILE_CAVE_11].h = TILE_HEIGHT;

	clips[TILE_RAMP].x = 40;
	clips[TILE_RAMP].y = 0;
	clips[TILE_RAMP].w = TILE_WIDTH;
	clips[TILE_RAMP].h = TILE_HEIGHT;

	clips[TILE_ROCK].x = 60;
	clips[TILE_ROCK].y = 0;
	clips[TILE_ROCK].w = TILE_WIDTH;
	clips[TILE_ROCK].h = TILE_HEIGHT;

	clips[TILE_COCONUT_00].x = 40;
	clips[TILE_COCONUT_00].y = 20;
	clips[TILE_COCONUT_00].w = TILE_WIDTH;
	clips[TILE_COCONUT_00].h = TILE_HEIGHT;

	clips[TILE_COCONUT_01].x = 60;
	clips[TILE_COCONUT_01].y = 20;
	clips[TILE_COCONUT_01].w = TILE_WIDTH;
	clips[TILE_COCONUT_01].h = TILE_HEIGHT;

	clips[TILE_COCONUT_10].x = 40;
	clips[TILE_COCONUT_10].y = 40;
	clips[TILE_COCONUT_10].w = TILE_WIDTH;
	clips[TILE_COCONUT_10].h = TILE_HEIGHT;

	clips[TILE_COCONUT_11].x = 60;
	clips[TILE_COCONUT_11].y = 40;
	clips[TILE_COCONUT_11].w = TILE_WIDTH;
	clips[TILE_COCONUT_11].h = TILE_HEIGHT;

	//FOR MOUNTAIN WATER FALL Right side
	clips[TILE_POUND_RIGHT_P1].x = 80;
	clips[TILE_POUND_RIGHT_P1].y = 20;
	clips[TILE_POUND_RIGHT_P1].w = TILE_WIDTH;
	clips[TILE_POUND_RIGHT_P1].h = TILE_HEIGHT;

	clips[TILE_POUND_RIGHT_P2].x = 100;
	clips[TILE_POUND_RIGHT_P2].y = 20;
	clips[TILE_POUND_RIGHT_P2].w = TILE_WIDTH;
	clips[TILE_POUND_RIGHT_P2].h = TILE_HEIGHT;

	clips[TILE_POUND_RIGHT_P3].x = 120;
	clips[TILE_POUND_RIGHT_P3].y = 20;
	clips[TILE_POUND_RIGHT_P3].w = TILE_WIDTH;
	clips[TILE_POUND_RIGHT_P3].h = TILE_HEIGHT;

	clips[TILE_POUND_RIGHT_P4].x = 140;
	clips[TILE_POUND_RIGHT_P4].y = 20;
	clips[TILE_POUND_RIGHT_P4].w = TILE_WIDTH;
	clips[TILE_POUND_RIGHT_P4].h = TILE_HEIGHT;

	clips[TILE_POUND_RIGHT_P5].x = 160;
	clips[TILE_POUND_RIGHT_P5].y = 20;
	clips[TILE_POUND_RIGHT_P5].w = TILE_WIDTH;
	clips[TILE_POUND_RIGHT_P5].h = TILE_HEIGHT;

	clips[TILE_POUND_RIGHT_P6].x = 180;
	clips[TILE_POUND_RIGHT_P6].y = 20;
	clips[TILE_POUND_RIGHT_P6].w = TILE_WIDTH;
	clips[TILE_POUND_RIGHT_P6].h = TILE_HEIGHT;

	clips[TILE_POUND_RIGHT_P7].x = 80;
	clips[TILE_POUND_RIGHT_P7].y = 40;
	clips[TILE_POUND_RIGHT_P7].w = TILE_WIDTH;
	clips[TILE_POUND_RIGHT_P7].h = TILE_HEIGHT;

	clips[TILE_POUND_RIGHT_P8].x = 100;
	clips[TILE_POUND_RIGHT_P8].y = 40;
	clips[TILE_POUND_RIGHT_P8].w = TILE_WIDTH;
	clips[TILE_POUND_RIGHT_P8].h = TILE_HEIGHT;

	clips[TILE_POUND_RIGHT_P9].x = 120;
	clips[TILE_POUND_RIGHT_P9].y = 40;
	clips[TILE_POUND_RIGHT_P9].w = TILE_WIDTH;
	clips[TILE_POUND_RIGHT_P9].h = TILE_HEIGHT;

	clips[TILE_POUND_RIGHT_P10].x = 140;
	clips[TILE_POUND_RIGHT_P10].y = 40;
	clips[TILE_POUND_RIGHT_P10].w = TILE_WIDTH;
	clips[TILE_POUND_RIGHT_P10].h = TILE_HEIGHT;

	clips[TILE_POUND_RIGHT_P11].x = 160;
	clips[TILE_POUND_RIGHT_P11].y = 40;
	clips[TILE_POUND_RIGHT_P11].w = TILE_WIDTH;
	clips[TILE_POUND_RIGHT_P11].h = TILE_HEIGHT;

	clips[TILE_POUND_RIGHT_P12].x = 180;
	clips[TILE_POUND_RIGHT_P12].y = 40;
	clips[TILE_POUND_RIGHT_P12].w = TILE_WIDTH;
	clips[TILE_POUND_RIGHT_P12].h = TILE_HEIGHT;

	clips[TILE_POUND_RIGHT_P13].x = 80;
	clips[TILE_POUND_RIGHT_P13].y = 60;
	clips[TILE_POUND_RIGHT_P13].w = TILE_WIDTH;
	clips[TILE_POUND_RIGHT_P13].h = TILE_HEIGHT;

	clips[TILE_POUND_RIGHT_P14].x = 100;
	clips[TILE_POUND_RIGHT_P14].y = 60;
	clips[TILE_POUND_RIGHT_P14].w = TILE_WIDTH;
	clips[TILE_POUND_RIGHT_P14].h = TILE_HEIGHT;

	clips[TILE_POUND_RIGHT_P15].x = 120;
	clips[TILE_POUND_RIGHT_P15].y = 60;
	clips[TILE_POUND_RIGHT_P15].w = TILE_WIDTH;
	clips[TILE_POUND_RIGHT_P15].h = TILE_HEIGHT;

	clips[TILE_POUND_RIGHT_P16].x = 140;
	clips[TILE_POUND_RIGHT_P16].y = 60;
	clips[TILE_POUND_RIGHT_P16].w = TILE_WIDTH;
	clips[TILE_POUND_RIGHT_P16].h = TILE_HEIGHT;

	clips[TILE_POUND_RIGHT_P17].x = 160;
	clips[TILE_POUND_RIGHT_P17].y = 60;
	clips[TILE_POUND_RIGHT_P17].w = TILE_WIDTH;
	clips[TILE_POUND_RIGHT_P17].h = TILE_HEIGHT;

	clips[TILE_POUND_RIGHT_P18].x = 180;
	clips[TILE_POUND_RIGHT_P18].y = 60;
	clips[TILE_POUND_RIGHT_P18].w = TILE_WIDTH;
	clips[TILE_POUND_RIGHT_P18].h = TILE_HEIGHT;

	clips[TILE_POUND_RIGHT_P19].x = 80;
	clips[TILE_POUND_RIGHT_P19].y = 80;
	clips[TILE_POUND_RIGHT_P19].w = TILE_WIDTH;
	clips[TILE_POUND_RIGHT_P19].h = TILE_HEIGHT;

	clips[TILE_POUND_RIGHT_P20].x = 100;
	clips[TILE_POUND_RIGHT_P20].y = 80;
	clips[TILE_POUND_RIGHT_P20].w = TILE_WIDTH;
	clips[TILE_POUND_RIGHT_P20].h = TILE_HEIGHT;

	clips[TILE_POUND_RIGHT_P21].x = 120;
	clips[TILE_POUND_RIGHT_P21].y = 80;
	clips[TILE_POUND_RIGHT_P21].w = TILE_WIDTH;
	clips[TILE_POUND_RIGHT_P21].h = TILE_HEIGHT;

	clips[TILE_POUND_RIGHT_P22].x = 140;
	clips[TILE_POUND_RIGHT_P22].y = 80;
	clips[TILE_POUND_RIGHT_P22].w = TILE_WIDTH;
	clips[TILE_POUND_RIGHT_P22].h = TILE_HEIGHT;

	clips[TILE_POUND_RIGHT_P23].x = 160;
	clips[TILE_POUND_RIGHT_P23].y = 80;
	clips[TILE_POUND_RIGHT_P23].w = TILE_WIDTH;
	clips[TILE_POUND_RIGHT_P23].h = TILE_HEIGHT;

	clips[TILE_POUND_RIGHT_P24].x = 180;
	clips[TILE_POUND_RIGHT_P24].y = 80;
	clips[TILE_POUND_RIGHT_P24].w = TILE_WIDTH;
	clips[TILE_POUND_RIGHT_P24].h = TILE_HEIGHT;

	//FOR MOUNTAIN WATER FALL Left side
	clips[TILE_POUND_LEFT_P1].x = 200;
	clips[TILE_POUND_LEFT_P1].y = 20;
	clips[TILE_POUND_LEFT_P1].w = TILE_WIDTH;
	clips[TILE_POUND_LEFT_P1].h = TILE_HEIGHT;

	clips[TILE_POUND_LEFT_P2].x = 220;
	clips[TILE_POUND_LEFT_P2].y = 20;
	clips[TILE_POUND_LEFT_P2].w = TILE_WIDTH;
	clips[TILE_POUND_LEFT_P2].h = TILE_HEIGHT;

	clips[TILE_POUND_LEFT_P3].x = 240;
	clips[TILE_POUND_LEFT_P3].y = 20;
	clips[TILE_POUND_LEFT_P3].w = TILE_WIDTH;
	clips[TILE_POUND_LEFT_P3].h = TILE_HEIGHT;

	clips[TILE_POUND_LEFT_P4].x = 260;
	clips[TILE_POUND_LEFT_P4].y = 20;
	clips[TILE_POUND_LEFT_P4].w = TILE_WIDTH;
	clips[TILE_POUND_LEFT_P4].h = TILE_HEIGHT;

	clips[TILE_POUND_LEFT_P5].x = 280;
	clips[TILE_POUND_LEFT_P5].y = 20;
	clips[TILE_POUND_LEFT_P5].w = TILE_WIDTH;
	clips[TILE_POUND_LEFT_P5].h = TILE_HEIGHT;

	clips[TILE_POUND_LEFT_P6].x = 300;
	clips[TILE_POUND_LEFT_P6].y = 20;
	clips[TILE_POUND_LEFT_P6].w = TILE_WIDTH;
	clips[TILE_POUND_LEFT_P6].h = TILE_HEIGHT;

	clips[TILE_POUND_LEFT_P7].x = 200;
	clips[TILE_POUND_LEFT_P7].y = 40;
	clips[TILE_POUND_LEFT_P7].w = TILE_WIDTH;
	clips[TILE_POUND_LEFT_P7].h = TILE_HEIGHT;

	clips[TILE_POUND_LEFT_P8].x = 220;
	clips[TILE_POUND_LEFT_P8].y = 40;
	clips[TILE_POUND_LEFT_P8].w = TILE_WIDTH;
	clips[TILE_POUND_LEFT_P8].h = TILE_HEIGHT;

	clips[TILE_POUND_LEFT_P9].x = 240;
	clips[TILE_POUND_LEFT_P9].y = 40;
	clips[TILE_POUND_LEFT_P9].w = TILE_WIDTH;
	clips[TILE_POUND_LEFT_P9].h = TILE_HEIGHT;

	clips[TILE_POUND_LEFT_P10].x = 260;
	clips[TILE_POUND_LEFT_P10].y = 40;
	clips[TILE_POUND_LEFT_P10].w = TILE_WIDTH;
	clips[TILE_POUND_LEFT_P10].h = TILE_HEIGHT;

	clips[TILE_POUND_LEFT_P11].x = 280;
	clips[TILE_POUND_LEFT_P11].y = 40;
	clips[TILE_POUND_LEFT_P11].w = TILE_WIDTH;
	clips[TILE_POUND_LEFT_P11].h = TILE_HEIGHT;

	clips[TILE_POUND_LEFT_P12].x = 300;
	clips[TILE_POUND_LEFT_P12].y = 40;
	clips[TILE_POUND_LEFT_P12].w = TILE_WIDTH;
	clips[TILE_POUND_LEFT_P12].h = TILE_HEIGHT;

	clips[TILE_POUND_LEFT_P13].x = 200;
	clips[TILE_POUND_LEFT_P13].y = 60;
	clips[TILE_POUND_LEFT_P13].w = TILE_WIDTH;
	clips[TILE_POUND_LEFT_P13].h = TILE_HEIGHT;

	clips[TILE_POUND_LEFT_P14].x = 220;
	clips[TILE_POUND_LEFT_P14].y = 60;
	clips[TILE_POUND_LEFT_P14].w = TILE_WIDTH;
	clips[TILE_POUND_LEFT_P14].h = TILE_HEIGHT;

	clips[TILE_POUND_LEFT_P15].x = 240;
	clips[TILE_POUND_LEFT_P15].y = 60;
	clips[TILE_POUND_LEFT_P15].w = TILE_WIDTH;
	clips[TILE_POUND_LEFT_P15].h = TILE_HEIGHT;

	clips[TILE_POUND_LEFT_P16].x = 260;
	clips[TILE_POUND_LEFT_P16].y = 60;
	clips[TILE_POUND_LEFT_P16].w = TILE_WIDTH;
	clips[TILE_POUND_LEFT_P16].h = TILE_HEIGHT;

	clips[TILE_POUND_LEFT_P17].x = 280;
	clips[TILE_POUND_LEFT_P17].y = 60;
	clips[TILE_POUND_LEFT_P17].w = TILE_WIDTH;
	clips[TILE_POUND_LEFT_P17].h = TILE_HEIGHT;

	clips[TILE_POUND_LEFT_P18].x = 300;
	clips[TILE_POUND_LEFT_P18].y = 60;
	clips[TILE_POUND_LEFT_P18].w = TILE_WIDTH;
	clips[TILE_POUND_LEFT_P18].h = TILE_HEIGHT;

	clips[TILE_POUND_LEFT_P19].x = 200;
	clips[TILE_POUND_LEFT_P19].y = 80;
	clips[TILE_POUND_LEFT_P19].w = TILE_WIDTH;
	clips[TILE_POUND_LEFT_P19].h = TILE_HEIGHT;

	clips[TILE_POUND_LEFT_P20].x = 220;
	clips[TILE_POUND_LEFT_P20].y = 80;
	clips[TILE_POUND_LEFT_P20].w = TILE_WIDTH;
	clips[TILE_POUND_LEFT_P20].h = TILE_HEIGHT;

	clips[TILE_POUND_LEFT_P21].x = 240;
	clips[TILE_POUND_LEFT_P21].y = 80;
	clips[TILE_POUND_LEFT_P21].w = TILE_WIDTH;
	clips[TILE_POUND_LEFT_P21].h = TILE_HEIGHT;

	clips[TILE_POUND_LEFT_P22].x = 260;
	clips[TILE_POUND_LEFT_P22].y = 80;
	clips[TILE_POUND_LEFT_P22].w = TILE_WIDTH;
	clips[TILE_POUND_LEFT_P22].h = TILE_HEIGHT;

	clips[TILE_POUND_LEFT_P23].x = 280;
	clips[TILE_POUND_LEFT_P23].y = 80;
	clips[TILE_POUND_LEFT_P23].w = TILE_WIDTH;
	clips[TILE_POUND_LEFT_P23].h = TILE_HEIGHT;

	clips[TILE_POUND_LEFT_P24].x = 300;
	clips[TILE_POUND_LEFT_P24].y = 80;
	clips[TILE_POUND_LEFT_P24].w = TILE_WIDTH;
	clips[TILE_POUND_LEFT_P24].h = TILE_HEIGHT;

	clips[TILE_KEY_LEFT].x = 100;
	clips[TILE_KEY_LEFT].y = 0;
	clips[TILE_KEY_LEFT].w = TILE_WIDTH;
	clips[TILE_KEY_LEFT].h = TILE_HEIGHT;

	clips[TILE_KEY_RIGHT].x = 124;
	clips[TILE_KEY_RIGHT].y = 0;
	clips[TILE_KEY_RIGHT].w = TILE_WIDTH;
	clips[TILE_KEY_RIGHT].h = TILE_HEIGHT;

	clips[TILE_KEY_LEFT_01].x = 100;
	clips[TILE_KEY_LEFT_01].y = 0;
	clips[TILE_KEY_LEFT_01].w = TILE_WIDTH;
	clips[TILE_KEY_LEFT_01].h = TILE_HEIGHT;

	clips[TILE_KEY_RIGHT_01].x = 124;
	clips[TILE_KEY_RIGHT_01].y = 0;
	clips[TILE_KEY_RIGHT_01].w = TILE_WIDTH;
	clips[TILE_KEY_RIGHT_01].h = TILE_HEIGHT;

	clips[TILE_DOOR_OPEN_LEFT_01].x = 320;
	clips[TILE_DOOR_OPEN_LEFT_01].y = 0;
	clips[TILE_DOOR_OPEN_LEFT_01].w = TILE_WIDTH;
	clips[TILE_DOOR_OPEN_LEFT_01].h = TILE_HEIGHT;

	clips[TILE_DOOR_OPEN_LEFT_02].x = 320;
	clips[TILE_DOOR_OPEN_LEFT_02].y = 20;
	clips[TILE_DOOR_OPEN_LEFT_02].w = TILE_WIDTH;
	clips[TILE_DOOR_OPEN_LEFT_02].h = TILE_HEIGHT;

	clips[TILE_DOOR_OPEN_RIGHT_01].x = 320;
	clips[TILE_DOOR_OPEN_RIGHT_01].y = 0;
	clips[TILE_DOOR_OPEN_RIGHT_01].w = TILE_WIDTH;
	clips[TILE_DOOR_OPEN_RIGHT_01].h = TILE_HEIGHT;

	clips[TILE_DOOR_OPEN_RIGHT_02].x = 320;
	clips[TILE_DOOR_OPEN_RIGHT_02].y = 20;
	clips[TILE_DOOR_OPEN_RIGHT_02].w = TILE_WIDTH;
	clips[TILE_DOOR_OPEN_RIGHT_02].h = TILE_HEIGHT;

	clips[TILE_DOOR_OPEN_LEFT_05].x = 320;
	clips[TILE_DOOR_OPEN_LEFT_05].y = 0;
	clips[TILE_DOOR_OPEN_LEFT_05].w = TILE_WIDTH;
	clips[TILE_DOOR_OPEN_LEFT_05].h = TILE_HEIGHT;

	clips[TILE_DOOR_OPEN_LEFT_06].x = 320;
	clips[TILE_DOOR_OPEN_LEFT_06].y = 20;
	clips[TILE_DOOR_OPEN_LEFT_06].w = TILE_WIDTH;
	clips[TILE_DOOR_OPEN_LEFT_06].h = TILE_HEIGHT;

	clips[TILE_DOOR_OPEN_RIGHT_05].x = 320;
	clips[TILE_DOOR_OPEN_RIGHT_05].y = 0;
	clips[TILE_DOOR_OPEN_RIGHT_05].w = TILE_WIDTH;
	clips[TILE_DOOR_OPEN_RIGHT_05].h = TILE_HEIGHT;

	clips[TILE_DOOR_OPEN_RIGHT_06].x = 320;
	clips[TILE_DOOR_OPEN_RIGHT_06].y = 20;
	clips[TILE_DOOR_OPEN_RIGHT_06].w = TILE_WIDTH;
	clips[TILE_DOOR_OPEN_RIGHT_06].h = TILE_HEIGHT;

}



#endif